### PR TITLE
KiCAD HAT Template

### PR DESCRIPTION
**Pull request by MTolba**

### CODE REVIEW

**Comment by MTolba** [comment]
I'm working on fixing the 3D model issue.

**Comment by ntzovanis** [comment]
Besides fixing the location of the 3D model, the schematic symbol of the HAT header should have the pins in the same position as the physical layout. That makes it easier to read when looking for a particular pin on the board.

**Comment by MTolba** [comment]
@ntzovanis 
I fixed the 3D model issue and converted the male pin headers to female ones. Then added a release with the Raspberry Pi header pin grouped.

Then I modified the schematics symbol to match the physical header layout and added this to another release.

So customers can choose whatever they prefer. 

Please take a look on both designs and approve it everything is okay.

**Review by ntzovanis — APPROVED** [review]
Looks good to me. Next time remember to remove the [WiP] from the PR when it's ready to be reviewed.

**Pull request merged**
