### PR TITLE
Adds meta data to KiCAD template

### PR DESCRIPTION
**Pull request by Bucknalla**
Cleans up meta data for KiCAD template and organises file structure for projects.

Change-type: minor
Signed-off-by: Alex Bucknall <alexbucknall@balena.io>

### CODE REVIEW

**Comment by Bucknalla** [comment]
Important files are in here -> Hat_Template/v1.1/KiCAD/meta

**Comment by Bucknalla** [comment]
Meta data allows for the template info to be easily seen from the template selection screen on KiCAD

**Comment by ntzovanis** [comment]
@MTolba can you check this?

**Comment by MTolba** [comment]
@ntzovanis 
I discovered that you added the .pro extensions to the gitignore file to ignore the autorouter files for Eagle but .pro is the project file for KiCAD.

Also, we need to add (.PrjPCBStructure) to the gitignore file.

@Bucknalla The project looks cleaner for me now.

**Comment by ntzovanis** [comment]
@MTolba nice catch!

**Comment by MTolba** [comment]
@ntzovanis  Should we approve @Bucknalla PR then make a new branch to fix the gitignore file?

**Comment by ntzovanis** [comment]
@MTolba if you've reviewed it, then we can approve it.

**Review by MTolba — COMMENTED** [review]
@Bucknalla Could you please make sure of the aspect ratio of the image you added to the metadata file?

**Comment by MTolba** [comment]
> @MTolba if you've reviewed it, then we can approve it.

I didn't review the designs, I guess Alex only modified the project structure and added the metadata file, Right?

**Review by MTolba — APPROVED** [review]

**Pull request merged**
